export const GET_NOTIFICATIONS = 'GET_NOTIFICATIONS';
export const GET_NOTIFICATIONS_SUCCESS = 'GET_NOTIFICATIONS_SUCCESS';
export const GET_NOTIFICATIONS_FAILURE = 'GET_NOTIFICATIONS_FAILURE';

export const POST_NOTIFICATION = 'POST_NOTIFICATION';
export const POST_NOTIFICATION_SUCCESS = 'POST_NOTIFICATION_SUCCESS';
export const POST_NOTIFICATION_FAILURE = 'POST_NOTIFICATION_FAILURE';

export const DELETE_NOTIFICATIONS = 'DELETE_NOTIFICATIONS';
export const DELETE_NOTIFICATIONS_SUCCESS = 'DELETE_NOTIFICATIONS_SUCCESS';
export const DELETE_NOTIFICATIONS_FAILURE = 'DELETE_NOTIFICATIONS_FAILURE';

export const PUT_NOTIFICATION = 'PUT_NOTIFICATION';
export const PUT_NOTIFICATION_SUCCESS = 'PUT_NOTIFICATION_SUCCESS';
export const PUT_NOTIFICATION_FAILURE = 'PUT_NOTIFICATION_FAILURE';
