export const CURRENCY_LOOKUP = {
  AED: { flag: 'ae', name: 'UAE Dirham' },
  AFN: { flag: 'af', name: 'Afghani' },
  ALL: { flag: 'al', name: 'Lek' },
  AMD: { flag: 'am', name: 'Armenian Dram' },
  ANG: { flag: 'cw', name: 'Netherlands Antillean Guilder' },
  AOA: { flag: 'ao', name: 'Kwanza' },
  ARS: { flag: 'ar', name: 'Argentine Peso' },
  AUD: { flag: 'au', name: 'Australian Dollar' },
  AWG: { flag: 'aw', name: 'Aruban Florin' },
  AZN: { flag: 'az', name: 'Azerbaijanian Manat' },
  BAM: { flag: 'ba', name: 'Convertible Mark' },
  BBD: { flag: 'bb', name: 'Barbados Dollar' },
  BDT: { flag: 'bd', name: 'Taka' },
  BGN: { flag: 'bg', name: 'Bulgarian Lev' },
  BHD: { flag: 'bh', name: 'Bahraini Dinar' },
  BIF: { flag: 'bi', name: 'Burundi Franc' },
  BMD: { flag: 'bm', name: 'Bermudian Dollar' },
  BND: { flag: 'bn', name: 'Brunei Dollar' },
  BOB: { flag: 'bo', name: 'Boliviano' },
  BOV: { flag: 'bo', name: 'Mvdol' },
  BRL: { flag: 'br', name: 'Brazilian Real' },
  BSD: { flag: 'bs', name: 'Bahamian Dollar' },
  BTN: { flag: 'bt', name: 'Ngultrum' },
  BWP: { flag: 'bw', name: 'Pula' },
  BYN: { flag: 'by', name: 'Belarussian Ruble' },
  BZD: { flag: 'bz', name: 'Belize Dollar' },
  CAD: { flag: 'ca', name: 'Canadian Dollar' },
  CDF: { flag: 'cd', name: 'Congolese Franc' },
  CHE: { flag: 'ch', name: 'WIR Euro' },
  CHF: { flag: 'ch', name: 'Swiss Franc' },
  CHW: { flag: 'ch', name: 'WIR Franc' },
  CLF: { flag: 'cl', name: 'Unidad de Fomento' },
  CLP: { flag: 'cl', name: 'Chilean Peso' },
  CNY: { flag: 'cn', name: 'Yuan Renminbi' },
  COP: { flag: 'co', name: 'Colombian Peso' },
  COU: { flag: 'co', name: 'Unidad de Valor Real' },
  CRC: { flag: 'cr', name: 'Costa Rican Colon' },
  CUC: { flag: 'cu', name: 'Peso Convertible' },
  CUP: { flag: 'cu', name: 'Cuban Peso' },
  CVE: { flag: 'cv', name: 'Cabo Verde Escudo' },
  CZK: { flag: 'cz', name: 'Czech Koruna' },
  DJF: { flag: 'dj', name: 'Djibouti Franc' },
  DKK: { flag: 'dk', name: 'Danish Krone' },
  DOP: { flag: 'do', name: 'Dominican Peso' },
  DZD: { flag: 'ec', name: 'Algerian Dinar' },
  EGP: { flag: 'eh', name: 'Egyptian Pound' },
  ERN: { flag: 'es', name: 'Nakfa' },
  ETB: { flag: 'et', name: 'Ethiopian Birr' },
  EUR: { flag: 'eu', name: 'Euro' },
  FJD: { flag: 'fj', name: 'Fiji Dollar' },
  FKP: { flag: 'fk', name: 'Falkland Islands Pound' },
  GBP: { flag: 'gb', name: 'Pound Sterling' },
  GEL: { flag: 'ge', name: 'Lari' },
  GHS: { flag: 'gh', name: 'Ghana Cedi' },
  GIP: { flag: 'gi', name: 'Gibraltar Pound' },
  GMD: { flag: 'gm', name: 'Dalasi' },
  GNF: { flag: 'gn', name: 'Guinea Franc' },
  GTQ: { flag: 'gt', name: 'Quetzal' },
  GYD: { flag: 'gy', name: 'Guyana Dollar' },
  HKD: { flag: 'hk', name: 'Hong Kong Dollar' },
  HNL: { flag: 'hn', name: 'Lempira' },
  HRK: { flag: 'hr', name: 'Kuna' },
  HTG: { flag: 'ht', name: 'Gourde' },
  HUF: { flag: 'hu', name: 'Forint' },
  IDR: { flag: 'id', name: 'Rupiah' },
  ILS: { flag: 'il', name: 'New Israeli Sheqel' },
  INR: { flag: 'in', name: 'Indian Rupee' },
  IQD: { flag: 'iq', name: 'Iraqi Dinar' },
  IRR: { flag: 'ir', name: 'Iranian Rial' },
  ISK: { flag: 'is', name: 'Iceland Krona' },
  JMD: { flag: 'jm', name: 'Jamaican Dollar' },
  JOD: { flag: 'jo', name: 'Jordanian Dinar' },
  JPY: { flag: 'jp', name: 'Yen' },
  KES: { flag: 'ke', name: 'Kenyan Shilling' },
  KGS: { flag: 'kg', name: 'Som' },
  KHR: { flag: 'kh', name: 'Riel' },
  KMF: { flag: 'km', name: 'Comoro Franc' },
  KPW: { flag: 'kp', name: 'North Korean Won' },
  KRW: { flag: 'kr', name: 'Won' },
  KWD: { flag: 'kw', name: 'Kuwaiti Dinar' },
  KYD: { flag: 'ky', name: 'Cayman Islands Dollar' },
  KZT: { flag: 'kz', name: 'Tenge' },
  LAK: { flag: 'la', name: 'Kip' },
  LBP: { flag: 'lb', name: 'Lebanese Pound' },
  LKR: { flag: 'lk', name: 'Sri Lanka Rupee' },
  LRD: { flag: 'lr', name: 'Liberian Dollar' },
  LSL: { flag: 'ls', name: 'Loti' },
  LYD: { flag: 'ly', name: 'Libyan Dinar' },
  MAD: { flag: 'ma', name: 'Moroccan Dirham' },
  MDL: { flag: 'md', name: 'Moldovan Leu' },
  MGA: { flag: 'mg', name: 'Malagasy Ariary' },
  MKD: { flag: 'mk', name: 'Denar' },
  MMK: { flag: 'mm', name: 'Kyat' },
  MNT: { flag: 'mn', name: 'Tugrik' },
  MOP: { flag: 'mo', name: 'Pataca' },
  MRU: { flag: 'mr', name: 'Ouguiya' },
  MUR: { flag: 'mu', name: 'Mauritius Rupee' },
  MVR: { flag: 'mv', name: 'Rufiyaa' },
  MWK: { flag: 'mw', name: 'Kwacha' },
  MXN: { flag: 'mx', name: 'Mexican Peso' },
  MXV: { flag: 'mx', name: 'Mexican Unidad de Inversion (UDI)' },
  MYR: { flag: 'my', name: 'Malaysian Ringgit' },
  MZN: { flag: 'mz', name: 'Mozambique Metical' },
  NAD: { flag: 'na', name: 'Namibia Dollar' },
  NGN: { flag: 'ng', name: 'Naira' },
  NIO: { flag: 'ni', name: 'Cordoba Oro' },
  NOK: { flag: 'no', name: 'Norwegian Krone' },
  NPR: { flag: 'np', name: 'Nepalese Rupee' },
  NZD: { flag: 'nz', name: 'New Zealand Dollar' },
  OMR: { flag: 'om', name: 'Rial Omani' },
  PAB: { flag: 'pa', name: 'Balboa' },
  PEN: { flag: 'pe', name: 'Nuevo Sol' },
  PGK: { flag: 'pg', name: 'Kina' },
  PHP: { flag: 'ph', name: 'Philippine Peso' },
  PKR: { flag: 'pk', name: 'Pakistan Rupee' },
  PLN: { flag: 'pl', name: 'Zloty' },
  PYG: { flag: 'py', name: 'Guarani' },
  QAR: { flag: 'qa', name: 'Qatari Rial' },
  RON: { flag: 'ro', name: 'Romanian Leu' },
  RSD: { flag: 'rs', name: 'Serbian Dinar' },
  RUB: { flag: 'ru', name: 'Russian Ruble' },
  RWF: { flag: 'rw', name: 'Rwanda Franc' },
  SAR: { flag: 'sa', name: 'Saudi Riyal' },
  SBD: { flag: 'sb', name: 'Solomon Islands Dollar' },
  SCR: { flag: 'sc', name: 'Seychelles Rupee' },
  SDG: { flag: 'sd', name: 'Sudanese Pound' },
  SEK: { flag: 'se', name: 'Swedish Krona' },
  SGD: { flag: 'sg', name: 'Singapore Dollar' },
  SHP: { flag: 'sh', name: 'Saint Helena Pound' },
  SLL: { flag: 'sl', name: 'Leone' },
  SOS: { flag: 'so', name: 'Somali Shilling' },
  SRD: { flag: 'sr', name: 'Surinam Dollar' },
  SSP: { flag: 'ss', name: 'South Sudanese Pound' },
  STN: { flag: 'st', name: 'Dobra' },
  SVC: { flag: 'sv', name: 'El Salvador Colon' },
  SYP: { flag: 'sy', name: 'Syrian Pound' },
  SZL: { flag: 'sz', name: 'Lilangeni' },
  THB: { flag: 'th', name: 'Baht' },
  TJS: { flag: 'tj', name: 'Somoni' },
  TMT: { flag: 'tm', name: 'Turkmenistan New Manat' },
  TND: { flag: 'tn', name: 'Tunisian Dinar' },
  TOP: { flag: 'to', name: 'Pa’anga' },
  TRY: { flag: 'tr', name: 'Turkish Lira' },
  TTD: { flag: 'tt', name: 'Trinidad and Tobago Dollar' },
  TWD: { flag: 'tw', name: 'New Taiwan Dollar' },
  TZS: { flag: 'tz', name: 'Tanzanian Shilling' },
  UAH: { flag: 'ua', name: 'Hryvnia' },
  UGX: { flag: 'ug', name: 'Uganda Shilling' },
  USD: { flag: 'us', name: 'US Dollar' },
  USN: { flag: 'us', name: 'US Dollar (Next day)' },
  UYI: { flag: 'uy', name: 'Uruguay Peso en Unidades Indexadas (URUIURUI)' },
  UYU: { flag: 'uy', name: 'Peso Uruguayo' },
  UZS: { flag: 'uz', name: 'Uzbekistan Sum' },
  VEF: { flag: 've', name: 'Bolivar' },
  VND: { flag: 'vn', name: 'Dong' },
  VUV: { flag: 'vu', name: 'Vatu' },
  WST: { flag: 'ws', name: 'Tala' },
  XAF: { flag: 'cf', name: 'CFA Franc BEAC' },
  XCD: { flag: null, name: 'East Caribbean Dollar' },
  XDR: { flag: null, name: 'SDR (Special Drawing Right)' },
  XOF: { flag: null, name: 'CFA Franc BCEAO' },
  XPF: { flag: null, name: 'CFP Franc' },
  XSU: { flag: null, name: 'Sucre' },
  XUA: { flag: null, name: 'ADB Unit of Account' },
  YER: { flag: 'ye', name: 'Yemeni Rial' },
  ZAR: { flag: 'za', name: 'Rand' },
  ZMW: { flag: 'zm', name: 'Zambian Kwacha' },
  ZWL: { flag: 'zw', name: 'Zimbabwe Dollar' },
};
