export const JWT_AUTH_SUCCESS = 'JWT_AUTH_SUCCESS';
export const JWT_AUTH_FAILURE = 'JWT_AUTH_FAILURE';

export const GET_ALL_USER_ROOMS_SUCCESS = 'GET_ALL_USER_ROOMS_SUCCESS';
export const GET_ALL_USER_ROOMS_FAILURE = 'GET_ALL_USER_ROOMS_FAILURE';
export const GET_ALLOWED_USER_ROOMS_SUCCESS = 'GET_ALLOWED_USER_ROOMS_SUCCESS';
export const GET_ALLOWED_USER_ROOMS_FAILURE = 'GET_ALLOWED_USER_ROOMS_FAILURE';

export const GET_USER_CONTACTS = 'GET_USER_CONTACTS';
export const GET_USER_CONTACTS_ERROR = 'GET_ALL_USER_ROOMS_FAILURE';
